### ISSUE TITLE
"java.lang.NoSuchMethodError: accessibilityHitTest" but the program functions properly

### ISSUE THREAD

**Issue by NRShao** [benfry/processing4#408]
## Description
As title says, this error pops up in console, even on a really simple program. 
![image](https://user-images.githubusercontent.com/14102516/153765736-7f6cb266-0815-4d6a-b3c4-1c135bfee391.png)

In my more complicated project, the project itself works perfectly fine, but still throws errors.

## Expected Behavior
Expected no errors

## Current Behavior
Currently, error pops up whenever I click the display window, and error pops up whenever I try to export the project.
Side note: Also expected that I can export, but it says "Error during export" with no additional details aside from
<img width="964" alt="image" src="https://user-images.githubusercontent.com/14102516/153765861-cbf39f8b-affd-403c-aa38-86488d2d6c9f.png">

## Steps to Reproduce
1. Code included in first screenshot above.
2. I went from fresh download -> open application -> write that -> error.
3.

## Your Environment

* Processing version: 4.0b5
* Operating System and OS version: MacOS Big Sur 11.6.3
* Other information: 

## Possible Causes / Solutions

I've tried to search for as many solutions as possible, and what people seem to think it boils down to in other applications, is a Java bug, but I installed JDK 17.0.2, and updated my java version. Not sure what other steps to take or other potential causes.

I haven't been able to find much information about this kind of error. Thanks in advance for your time, and if this is just something that I'm doing wrong, sorry for taking up time!

**Comment by benfry** [comment]
Yeah, I saw the error when exporting just recently, and already fixed it here: https://github.com/processing/processing4/commit/1bb5b3e60c5c954432d37051140f5ff1ab833a31 so that'll be resolved for 4.0 beta 6.

The `accessibilityHitTest` issue is a problem inside Java, see:
https://bugs.openjdk.java.net/browse/JDK-8274326
which it looks like it should be fixed in 17.0.2:
https://bugs.openjdk.java.net/browse/JDK-8274604

I'm trying to get beta 6 out now, which will have 17.0.2, so give that a shot and see if it happens again.

**Comment by NRShao** [comment]
Oh beautiful. Thanks for the quick reply!

**Comment by dkBrazz** [comment]
this is a possibly relevant issue reported on StackOverflow
https://stackoverflow.com/questions/71173094/

**Comment by benfry** [comment]
@dkBrazz Nope, that's https://github.com/processing/processing4/issues/409

**Comment by NRShao** [comment]
I updated to 4.0b6, and the exporting works!! however, it seems like the accessibilityHitTest issue with on click events is still happening.

**Comment by benfry** [comment]
Nuts, ok. Thanks for reporting back.

**Comment by NRShao** [comment]
ofc! It doesnt seem to impact the functionality of the programs I'm running, so after exporting I guess out of sight out of mind?

**Comment by benfry** [comment]
Yeah, fingers crossed… But also odd that it's listed as “fixed” in JDK 17.0.2 b1 (https://bugs.openjdk.java.net/browse/JDK-8274604).

**Comment by benfry** [comment]
Closing this one as duplicate of #368.
